### creating an friendship
POST http://localhost:5400/api/friendship
Content-Type: application/json

{
    "User1ID": "e081256d-796f-4dcc-9553-1959c887ce5f",
    "User2ID": "983a1822-6c89-478e-a228-6c73ea8d1d9a",
    "FriendshipDate": "01-02-2024"
}



###
# getting a single friendship
GET http://localhost:5400/api/friendship/15bf7912-a87b-4ed9-b0e0-da71fc28e4af
Content-Type: application/json


###
# get all friendship

GET http://localhost:5400/api/friendship/allfriends



### updating an friendship
PUT http://localhost:5400/api/friendship/update/15bf7912-a87b-4ed9-b0e0-da71fc28e4af
Content-Type: application/json

{
    "FriendshipDate": ""
}



###
# delete an event
DELETE http://localhost:5400/api/friendship/delete/15bf7912-a87b-4ed9-b0e0-da71fc28e4af