### creating an event
POST http://localhost:5400/api/events
Content-Type: application/json

{
    "EventName": "Target",
    "Description": "shooting at the range",
    "EventDate": "03-04-2024",
    "Location": "Nairobi",
    "EventPosterURL": "click here"
}



###
# getting a single event
GET http://localhost:5400/api/events/ceb87aaf-596d-494f-b28a-51be83902aac
Content-Type: application/json


###
# get all events

GET http://localhost:5400/api/events/allevents



### updating an event
PUT http://localhost:5400/api/events/update/ceb87aaf-596d-494f-b28a-51be83902aac
Content-Type: application/json

{
    "EventName": "Valentine is coming",
    "Description": "where is your boyfriend",
    "EventDate": "05-04-2024",
    "Location": "Everywhere",
    "EventPosterURL": "http://becks.com"
}



###
# delete an event
DELETE http://localhost:5400/api/events/delete/ceb87aaf-596d-494f-b28a-51be83902aac