### creating a group
POST http://localhost:5400/api/groupmembers
Content-Type: application/json

{
    "GroupID": "d14e25bb-a925-423d-a004-863778c84d62",
    "MemberID": "96b635c6-48e3-41ad-9551-543864fa7f0b"
}



###
# getting a single group
GET http://localhost:5400/api/groups/df62b93b-69af-446a-b8c1-e8fbf6c0860f
Content-Type: application/json


###
# get all groups

GET http://localhost:5400/api/groupmembers/d14e25bb-a925-423d-a004-863778c84d62/all



### updating a post
PUT http://localhost:5400/api/groupmembers/
Content-Type: application/json

{
    "GroupID": "d14e25bb-a925-423d-a004-863778c84d62"
}



###
# delete a post
DELETE http://localhost:5400/api/groupmembers/d14e25bb-a925-423d-a004-863778c84d62/96b635c6-48e3-41ad-9551-543864fa7f0b