### registering a user
POST http://localhost:5400/api/users
Content-Type: application/json

{
    "Username": "nyambuu",
    "Email" : "leahnyambura682@gmail.com",
    "Password" : "12345678",
    "TagName": "@kanyambu_kamama",
    "Location" : "Nyandarua,Kenya"
}



### loging in a user
POST http://localhost:5400/api/users/login
Content-Type: application/json

{
   
    "Email" : "leahnyambura682@gmail.com",
    "Password" : "12345678"
    
}




//send mail
###
GET http://localhost:5400/send-mail



###
# getting a single user
GET http://localhost:5400/api/users/20072356-9d6d-427b-9a0a-d02f1270a560
Content-Type: application/json



###
# get all users

GET http://localhost:5400/api/users/allusers




### updating a users
PUT http://localhost:5400/api/users/update/7309e1c5-8887-47c1-b4cd-603f8ce04839
Content-Type: application/json
authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYjE4YjlhYi1iYWE4LTQyYWQtYWVlYS00NGE2YjMwM2UxZjEiLCJpYXQiOjE3MDg3ODExNTUsImV4cCI6MTcwOTA0MDM1NX0.xdfVXc08ZvQSdmY6uoxH_c_gAhj8FRfku8nSxgVwXCM

{
    "Username": "nyambuu",
    "Email": "leahnyambura682@gmail.com",
    "TagName": "@kanyambu_kamama",
    "Location": "Nyandarua,Kenya",
    "Password" : "12345678"
  }



###
# delete a users
DELETE http://localhost:5400/api/users/delete/cdc66f64-cafe-4170-a2d8-f6d9c8e1f4cb
Content-Type: application/json
authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZGM2NmY2NC1jYWZlLTQxNzAtYTJkOC1mNmQ5YzhlMWY0Y2IiLCJpYXQiOjE3MDg3ODA3NDUsImV4cCI6MTcwOTAzOTk0NX0.xq9FvSg82scAVGkgH9WXl2Y2XdZ3YhKo48cyxxvuFGw